name: user_repo
description: repo that handles users
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'  

dependencies:
  flutter:
    sdk: flutter
  flutter95: ^1.0.0  

dev_dependencies:
  flutter_test:
    sdk: flutter

  firebase_auth: ^4.16.0
  cloud_firestore: ^4.9.2
  # equatable: ^2.0.5
  # firebase_storage: ^11.6.0
  rxdart: ^0.27.7
  # path: ^1.8.3

flutter:
  uses-material-design: true